// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.9
// source: pkg/flowkitgrpc/flowkit.proto

package flowkitgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthRequest is the input message for the HealthCheck method.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{0}
}

// HealthResponse is the output message for the HealthCheck method.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the health check, always "OK" for a healthy service.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// VersionRequest is the input message for the GetVersion method.
type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{2}
}

// VersionResponse is the output message for the GetVersion method.
type VersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version of the service.
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{3}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ListFunctionsRequest is the input message for the ListFunctions method.
// As no input is required, this message is empty.
type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{4}
}

// ListFunctionsResponse is the output message for the ListFunctions method.
// It contains a map of function names to their definitions.
type ListFunctionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of function names to their definitions.
	Functions     map[string]*FunctionDefinition `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{5}
}

func (x *ListFunctionsResponse) GetFunctions() map[string]*FunctionDefinition {
	if x != nil {
		return x.Functions
	}
	return nil
}

// FunctionDefinition is the definition of an individual function.
// It contains the name, description, inputs and outputs of the function.
type FunctionDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the function.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Category of the function.
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	// Display name of the function;
	DisplayName string `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// List of input definitions for the function.
	Input []*FunctionInputDefinition `protobuf:"bytes,5,rep,name=input,proto3" json:"input,omitempty"`
	// List of output definitions for the function.
	Output []*FunctionOutputDefinition `protobuf:"bytes,6,rep,name=output,proto3" json:"output,omitempty"`
	// List of deprecated parameters for the function.
	DeprecatedParams []string `protobuf:"bytes,7,rep,name=deprecatedParams,proto3" json:"deprecatedParams,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FunctionDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *FunctionDefinition) GetInput() []*FunctionInputDefinition {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *FunctionDefinition) GetOutput() []*FunctionOutputDefinition {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *FunctionDefinition) GetDeprecatedParams() []string {
	if x != nil {
		return x.DeprecatedParams
	}
	return nil
}

// FunctionInputDefinition is the definition of an input for a function.
// It contains the name, type, Go language type and options for the input.
type FunctionInputDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the input.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the input.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Go language type of the input.
	GoType string `protobuf:"bytes,3,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// List of options for the input, if applicable.
	Options       []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInputDefinition) Reset() {
	*x = FunctionInputDefinition{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInputDefinition) ProtoMessage() {}

func (x *FunctionInputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInputDefinition.ProtoReflect.Descriptor instead.
func (*FunctionInputDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionInputDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInputDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionInputDefinition) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *FunctionInputDefinition) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// FunctionOutputDefinition is the definition of an output for a function.
// It contains the name, type and Go language type of the output.
type FunctionOutputDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the output.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the output.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Go language type of the output.
	GoType        string `protobuf:"bytes,3,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionOutputDefinition) Reset() {
	*x = FunctionOutputDefinition{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOutputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOutputDefinition) ProtoMessage() {}

func (x *FunctionOutputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOutputDefinition.ProtoReflect.Descriptor instead.
func (*FunctionOutputDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{8}
}

func (x *FunctionOutputDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionOutputDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionOutputDefinition) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

// FunctionInputs is the input message for the RunFunction method.
// It contains the name of the function to run and a list of inputs.
type FunctionInputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function to run.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of inputs for the function.
	Inputs []*FunctionInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Type for return responses from agent to flowkit for other commands. "input" is the default and will start the function run. Other types: "approval_response"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Optional instruction ID only relevant for "approval_response" type.
	InstructionId string `protobuf:"bytes,4,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Optional approval response only relevant for "approval_response" type.
	ApprovalResponse string `protobuf:"bytes,5,opt,name=approval_response,json=approvalResponse,proto3" json:"approval_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FunctionInputs) Reset() {
	*x = FunctionInputs{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInputs) ProtoMessage() {}

func (x *FunctionInputs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInputs.ProtoReflect.Descriptor instead.
func (*FunctionInputs) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{9}
}

func (x *FunctionInputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInputs) GetInputs() []*FunctionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *FunctionInputs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionInputs) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *FunctionInputs) GetApprovalResponse() string {
	if x != nil {
		return x.ApprovalResponse
	}
	return ""
}

// Single input for a function.
type FunctionInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the input.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Go language type of the input.
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// Value of the input.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInput) Reset() {
	*x = FunctionInput{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInput) ProtoMessage() {}

func (x *FunctionInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInput.ProtoReflect.Descriptor instead.
func (*FunctionInput) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{10}
}

func (x *FunctionInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInput) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *FunctionInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// FunctionOutputs is the output message for the RunFunction method.
// It contains the name of the function that was run and a list of outputs.
type FunctionOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function that was run.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of outputs from the function.
	Outputs []*FunctionOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Type for running other commands from flowkit to agent. "response" is the default type for normal function outputs and will end the function run. Other types: "disable_interrupt", "enable_interrupt", "info_message", "status_message", "get_aprroval"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Optional message only relevant for "info_message" and "status_message" types.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Optional instruction ID only relevant for "get_approval" type.
	InstructionId string `protobuf:"bytes,5,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Optional approval text only relevant for "get_approval" type.
	ApprovalText string `protobuf:"bytes,6,opt,name=approval_text,json=approvalText,proto3" json:"approval_text,omitempty"`
	// Optional approval options only relevant for "get_approval" type; add "free_text" to allow free text input from the client.
	ApprovalOptions []string `protobuf:"bytes,7,rep,name=approval_options,json=approvalOptions,proto3" json:"approval_options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FunctionOutputs) Reset() {
	*x = FunctionOutputs{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOutputs) ProtoMessage() {}

func (x *FunctionOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOutputs.ProtoReflect.Descriptor instead.
func (*FunctionOutputs) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{11}
}

func (x *FunctionOutputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionOutputs) GetOutputs() []*FunctionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *FunctionOutputs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionOutputs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FunctionOutputs) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *FunctionOutputs) GetApprovalText() string {
	if x != nil {
		return x.ApprovalText
	}
	return ""
}

func (x *FunctionOutputs) GetApprovalOptions() []string {
	if x != nil {
		return x.ApprovalOptions
	}
	return nil
}

// FunctionOutput is a single output from a function.
// It contains the name, Go language type and value of the output.
type FunctionOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the output.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Go language type of the output.
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// Value of the output.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Code validation of the output. Only relevant for code generation.
	CodeValidation string `protobuf:"bytes,4,opt,name=code_validation,json=codeValidation,proto3" json:"code_validation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionOutput) Reset() {
	*x = FunctionOutput{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOutput) ProtoMessage() {}

func (x *FunctionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOutput.ProtoReflect.Descriptor instead.
func (*FunctionOutput) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionOutput) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *FunctionOutput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FunctionOutput) GetCodeValidation() string {
	if x != nil {
		return x.CodeValidation
	}
	return ""
}

// StreamInput is the input message for the bidirectional StreamFunction method.
// The first message should contain the function inputs. Subsequent messages can be used for interrupts.
type StreamInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function to run (only required in the first message).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of inputs for the function (only required in the first message).
	Inputs []*FunctionInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Type for send other commands from client to server. "input" is the default and will start the function run. Other types: "interrupt", "approval_response"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Interrupt message sent from client to server.
	Interrupt string `protobuf:"bytes,4,opt,name=interrupt,proto3" json:"interrupt,omitempty"`
	// Optional instruction ID only relevant for "approval_response" type.
	InstructionId string `protobuf:"bytes,5,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Optional approval response only relevant for "approval_response" type.
	ApprovalResponse string `protobuf:"bytes,6,opt,name=approval_response,json=approvalResponse,proto3" json:"approval_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamInput) Reset() {
	*x = StreamInput{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInput) ProtoMessage() {}

func (x *StreamInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInput.ProtoReflect.Descriptor instead.
func (*StreamInput) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{13}
}

func (x *StreamInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamInput) GetInputs() []*FunctionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *StreamInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamInput) GetInterrupt() string {
	if x != nil {
		return x.Interrupt
	}
	return ""
}

func (x *StreamInput) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *StreamInput) GetApprovalResponse() string {
	if x != nil {
		return x.ApprovalResponse
	}
	return ""
}

// StreamOutput is the output message for the StreamFunction method.
// It contains the message counter, a flag indicating if this is the last message
type StreamOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Counter for the message in the stream.
	MessageCounter int32 `protobuf:"varint,1,opt,name=message_counter,json=messageCounter,proto3" json:"message_counter,omitempty"`
	// Indicates if this is the last message in the stream.
	IsLast bool `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	// Value of the output.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Code validation of the output. Only relevant for code generation.
	CodeValidation string `protobuf:"bytes,4,opt,name=code_validation,json=codeValidation,proto3" json:"code_validation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOutput) Reset() {
	*x = StreamOutput{}
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutput) ProtoMessage() {}

func (x *StreamOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_flowkitgrpc_flowkit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutput.ProtoReflect.Descriptor instead.
func (*StreamOutput) Descriptor() ([]byte, []int) {
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP(), []int{14}
}

func (x *StreamOutput) GetMessageCounter() int32 {
	if x != nil {
		return x.MessageCounter
	}
	return 0
}

func (x *StreamOutput) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *StreamOutput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StreamOutput) GetCodeValidation() string {
	if x != nil {
		return x.CodeValidation
	}
	return ""
}

var File_pkg_flowkitgrpc_flowkit_proto protoreflect.FileDescriptor

const file_pkg_flowkitgrpc_flowkit_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/flowkitgrpc/flowkit.proto\x12\vflowkitgrpc\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x16\n" +
	"\x14ListFunctionsRequest\"\xc7\x01\n" +
	"\x15ListFunctionsResponse\x12O\n" +
	"\tfunctions\x18\x01 \x03(\v21.flowkitgrpc.ListFunctionsResponse.FunctionsEntryR\tfunctions\x1a]\n" +
	"\x0eFunctionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.flowkitgrpc.FunctionDefinitionR\x05value:\x028\x01\"\xaf\x02\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdisplayName\x18\x04 \x01(\tR\vdisplayName\x12:\n" +
	"\x05input\x18\x05 \x03(\v2$.flowkitgrpc.FunctionInputDefinitionR\x05input\x12=\n" +
	"\x06output\x18\x06 \x03(\v2%.flowkitgrpc.FunctionOutputDefinitionR\x06output\x12*\n" +
	"\x10deprecatedParams\x18\a \x03(\tR\x10deprecatedParams\"t\n" +
	"\x17FunctionInputDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\ago_type\x18\x03 \x01(\tR\x06goType\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"[\n" +
	"\x18FunctionOutputDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\ago_type\x18\x03 \x01(\tR\x06goType\"\xc0\x01\n" +
	"\x0eFunctionInputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06inputs\x18\x02 \x03(\v2\x1a.flowkitgrpc.FunctionInputR\x06inputs\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12%\n" +
	"\x0einstruction_id\x18\x04 \x01(\tR\rinstructionId\x12+\n" +
	"\x11approval_response\x18\x05 \x01(\tR\x10approvalResponse\"R\n" +
	"\rFunctionInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x81\x02\n" +
	"\x0fFunctionOutputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\aoutputs\x18\x02 \x03(\v2\x1b.flowkitgrpc.FunctionOutputR\aoutputs\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x0einstruction_id\x18\x05 \x01(\tR\rinstructionId\x12#\n" +
	"\rapproval_text\x18\x06 \x01(\tR\fapprovalText\x12)\n" +
	"\x10approval_options\x18\a \x03(\tR\x0fapprovalOptions\"|\n" +
	"\x0eFunctionOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12'\n" +
	"\x0fcode_validation\x18\x04 \x01(\tR\x0ecodeValidation\"\xdb\x01\n" +
	"\vStreamInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06inputs\x18\x02 \x03(\v2\x1a.flowkitgrpc.FunctionInputR\x06inputs\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tinterrupt\x18\x04 \x01(\tR\tinterrupt\x12%\n" +
	"\x0einstruction_id\x18\x05 \x01(\tR\rinstructionId\x12+\n" +
	"\x11approval_response\x18\x06 \x01(\tR\x10approvalResponse\"\x8f\x01\n" +
	"\fStreamOutput\x12'\n" +
	"\x0fmessage_counter\x18\x01 \x01(\x05R\x0emessageCounter\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12'\n" +
	"\x0fcode_validation\x18\x04 \x01(\tR\x0ecodeValidation2\x9f\x03\n" +
	"\x11ExternalFunctions\x12H\n" +
	"\vHealthCheck\x12\x1a.flowkitgrpc.HealthRequest\x1a\x1b.flowkitgrpc.HealthResponse\"\x00\x12I\n" +
	"\n" +
	"GetVersion\x12\x1b.flowkitgrpc.VersionRequest\x1a\x1c.flowkitgrpc.VersionResponse\"\x00\x12X\n" +
	"\rListFunctions\x12!.flowkitgrpc.ListFunctionsRequest\x1a\".flowkitgrpc.ListFunctionsResponse\"\x00\x12N\n" +
	"\vRunFunction\x12\x1b.flowkitgrpc.FunctionInputs\x1a\x1c.flowkitgrpc.FunctionOutputs\"\x00(\x010\x01\x12K\n" +
	"\x0eStreamFunction\x12\x18.flowkitgrpc.StreamInput\x1a\x19.flowkitgrpc.StreamOutput\"\x00(\x010\x01B\x0fZ\r./flowkitgrpcb\x06proto3"

var (
	file_pkg_flowkitgrpc_flowkit_proto_rawDescOnce sync.Once
	file_pkg_flowkitgrpc_flowkit_proto_rawDescData []byte
)

func file_pkg_flowkitgrpc_flowkit_proto_rawDescGZIP() []byte {
	file_pkg_flowkitgrpc_flowkit_proto_rawDescOnce.Do(func() {
		file_pkg_flowkitgrpc_flowkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_flowkitgrpc_flowkit_proto_rawDesc), len(file_pkg_flowkitgrpc_flowkit_proto_rawDesc)))
	})
	return file_pkg_flowkitgrpc_flowkit_proto_rawDescData
}

var file_pkg_flowkitgrpc_flowkit_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_flowkitgrpc_flowkit_proto_goTypes = []any{
	(*HealthRequest)(nil),            // 0: flowkitgrpc.HealthRequest
	(*HealthResponse)(nil),           // 1: flowkitgrpc.HealthResponse
	(*VersionRequest)(nil),           // 2: flowkitgrpc.VersionRequest
	(*VersionResponse)(nil),          // 3: flowkitgrpc.VersionResponse
	(*ListFunctionsRequest)(nil),     // 4: flowkitgrpc.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),    // 5: flowkitgrpc.ListFunctionsResponse
	(*FunctionDefinition)(nil),       // 6: flowkitgrpc.FunctionDefinition
	(*FunctionInputDefinition)(nil),  // 7: flowkitgrpc.FunctionInputDefinition
	(*FunctionOutputDefinition)(nil), // 8: flowkitgrpc.FunctionOutputDefinition
	(*FunctionInputs)(nil),           // 9: flowkitgrpc.FunctionInputs
	(*FunctionInput)(nil),            // 10: flowkitgrpc.FunctionInput
	(*FunctionOutputs)(nil),          // 11: flowkitgrpc.FunctionOutputs
	(*FunctionOutput)(nil),           // 12: flowkitgrpc.FunctionOutput
	(*StreamInput)(nil),              // 13: flowkitgrpc.StreamInput
	(*StreamOutput)(nil),             // 14: flowkitgrpc.StreamOutput
	nil,                              // 15: flowkitgrpc.ListFunctionsResponse.FunctionsEntry
}
var file_pkg_flowkitgrpc_flowkit_proto_depIdxs = []int32{
	15, // 0: flowkitgrpc.ListFunctionsResponse.functions:type_name -> flowkitgrpc.ListFunctionsResponse.FunctionsEntry
	7,  // 1: flowkitgrpc.FunctionDefinition.input:type_name -> flowkitgrpc.FunctionInputDefinition
	8,  // 2: flowkitgrpc.FunctionDefinition.output:type_name -> flowkitgrpc.FunctionOutputDefinition
	10, // 3: flowkitgrpc.FunctionInputs.inputs:type_name -> flowkitgrpc.FunctionInput
	12, // 4: flowkitgrpc.FunctionOutputs.outputs:type_name -> flowkitgrpc.FunctionOutput
	10, // 5: flowkitgrpc.StreamInput.inputs:type_name -> flowkitgrpc.FunctionInput
	6,  // 6: flowkitgrpc.ListFunctionsResponse.FunctionsEntry.value:type_name -> flowkitgrpc.FunctionDefinition
	0,  // 7: flowkitgrpc.ExternalFunctions.HealthCheck:input_type -> flowkitgrpc.HealthRequest
	2,  // 8: flowkitgrpc.ExternalFunctions.GetVersion:input_type -> flowkitgrpc.VersionRequest
	4,  // 9: flowkitgrpc.ExternalFunctions.ListFunctions:input_type -> flowkitgrpc.ListFunctionsRequest
	9,  // 10: flowkitgrpc.ExternalFunctions.RunFunction:input_type -> flowkitgrpc.FunctionInputs
	13, // 11: flowkitgrpc.ExternalFunctions.StreamFunction:input_type -> flowkitgrpc.StreamInput
	1,  // 12: flowkitgrpc.ExternalFunctions.HealthCheck:output_type -> flowkitgrpc.HealthResponse
	3,  // 13: flowkitgrpc.ExternalFunctions.GetVersion:output_type -> flowkitgrpc.VersionResponse
	5,  // 14: flowkitgrpc.ExternalFunctions.ListFunctions:output_type -> flowkitgrpc.ListFunctionsResponse
	11, // 15: flowkitgrpc.ExternalFunctions.RunFunction:output_type -> flowkitgrpc.FunctionOutputs
	14, // 16: flowkitgrpc.ExternalFunctions.StreamFunction:output_type -> flowkitgrpc.StreamOutput
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_flowkitgrpc_flowkit_proto_init() }
func file_pkg_flowkitgrpc_flowkit_proto_init() {
	if File_pkg_flowkitgrpc_flowkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_flowkitgrpc_flowkit_proto_rawDesc), len(file_pkg_flowkitgrpc_flowkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_flowkitgrpc_flowkit_proto_goTypes,
		DependencyIndexes: file_pkg_flowkitgrpc_flowkit_proto_depIdxs,
		MessageInfos:      file_pkg_flowkitgrpc_flowkit_proto_msgTypes,
	}.Build()
	File_pkg_flowkitgrpc_flowkit_proto = out.File
	file_pkg_flowkitgrpc_flowkit_proto_goTypes = nil
	file_pkg_flowkitgrpc_flowkit_proto_depIdxs = nil
}
