syntax = "proto3";

package flowkitgrpc;

option go_package = "./flowkitgrpc";

// ExternalFunctions is a gRPC service that allows for listing and running
// the function available in the externalfunctions package.
service ExternalFunctions {
  // HealthCheck is a simple health check method that returns an empty response.
  rpc HealthCheck(HealthRequest) returns (HealthResponse) {}

  // GetVersion returns the version of the service.
  rpc GetVersion(VersionRequest) returns (VersionResponse) {}

  // Lists all available functions with description, inputs and outputs.
  rpc ListFunctions(ListFunctionsRequest) returns (ListFunctionsResponse) {}

  // Runs a specified function with provided inputs and returns the function outputs.
  rpc RunFunction(stream FunctionInputs) returns (stream FunctionOutputs) {}

  // Runs a specified function with provided inputs and returns the function output as a stream.
  // Accepts a stream of StreamInput messages to allow client-to-server interrupts.
  rpc StreamFunction(stream StreamInput) returns (stream StreamOutput) {}
}

// HealthRequest is the input message for the HealthCheck method.
message HealthRequest {}

// HealthResponse is the output message for the HealthCheck method.
message HealthResponse {
  // Status of the health check, always "OK" for a healthy service.
  string status = 1;
}

// VersionRequest is the input message for the GetVersion method.
message VersionRequest {}

// VersionResponse is the output message for the GetVersion method.
message VersionResponse {
  // Version of the service.
  string version = 1;
}

// ListFunctionsRequest is the input message for the ListFunctions method.
// As no input is required, this message is empty.
message ListFunctionsRequest {}

// ListFunctionsResponse is the output message for the ListFunctions method.
// It contains a map of function names to their definitions.
message ListFunctionsResponse {
  // Map of function names to their definitions.
  map<string, FunctionDefinition> functions = 1;
}

// FunctionDefinition is the definition of an individual function.
// It contains the name, description, inputs and outputs of the function.
message FunctionDefinition {
  // Name of the function.
  string name = 1;

  // Description of the function.
  string description = 2;

  // Category of the function.
  string category = 3;

  // Display name of the function;
  string displayName = 4;

  // List of input definitions for the function.
  repeated FunctionInputDefinition input = 5;

  // List of output definitions for the function.
  repeated FunctionOutputDefinition output = 6;

  // List of deprecated parameters for the function.
  repeated string deprecatedParams = 7;
}

// FunctionInputDefinition is the definition of an input for a function.
// It contains the name, type, Go language type and options for the input.
message FunctionInputDefinition {
  // Name of the input.
  string name = 1;

  // Type of the input.
  string type = 2;

  // Go language type of the input.
  string go_type = 3;

  // List of options for the input, if applicable.
  repeated string options = 4;
}

// FunctionOutputDefinition is the definition of an output for a function.
// It contains the name, type and Go language type of the output.
message FunctionOutputDefinition {
  // Name of the output.
  string name = 1;

  // Type of the output.
  string type = 2;

  // Go language type of the output.
  string go_type = 3;
}

// FunctionInputs is the input message for the RunFunction method.
// It contains the name of the function to run and a list of inputs.
message FunctionInputs {
  // Name of the function to run.
  string name = 1;

  // List of inputs for the function.
  repeated FunctionInput inputs = 2;

  // Type for return responses from agent to flowkit for other commands. "input" is the default and will start the function run. Other types: "approval_response"
  string type = 3;

  // Optional instruction ID only relevant for "approval_response" type.
  string instruction_id = 4;

  // Optional approval response only relevant for "approval_response" type.
  string approval_response = 5;
}

// Single input for a function.
message FunctionInput {
  // Name of the input.
  string name = 1;

  // Go language type of the input.
  string go_type = 2;

  // Value of the input.
  string value = 3;
}

// FunctionOutputs is the output message for the RunFunction method.
// It contains the name of the function that was run and a list of outputs.
message FunctionOutputs {
  // Name of the function that was run.
  string name = 1;

  // List of outputs from the function.
  repeated FunctionOutput outputs = 2;

  // Type for running other commands from flowkit to agent. "response" is the default type for normal function outputs and will end the function run. Other types: "disable_interrupt", "enable_interrupt", "info_message", "status_message", "get_aprroval"
  string type = 3;

  // Optional message only relevant for "info_message" and "status_message" types.
  string message = 4;

  // Optional instruction ID only relevant for "get_approval" type.
  string instruction_id = 5;

  // Optional approval text only relevant for "get_approval" type.
  string approval_text = 6;

  // Optional approval options only relevant for "get_approval" type; add "free_text" to allow free text input from the client.
  repeated string approval_options = 7;
}

// FunctionOutput is a single output from a function.
// It contains the name, Go language type and value of the output.
message FunctionOutput {
  // Name of the output.
  string name = 1;

  // Go language type of the output.
  string go_type = 2;

  // Value of the output.
  string value = 3;

  // Code validation of the output. Only relevant for code generation.
  string code_validation = 4;
}

// StreamInput is the input message for the bidirectional StreamFunction method.
// The first message should contain the function inputs. Subsequent messages can be used for interrupts.
message StreamInput {
  // Name of the function to run (only required in the first message).
  string name = 1;

  // List of inputs for the function (only required in the first message).
  repeated FunctionInput inputs = 2;

  // Type for send other commands from client to server. "input" is the default and will start the function run. Other types: "interrupt", "approval_response"
  string type = 3;

  // Interrupt message sent from client to server.
  string interrupt = 4;

  // Optional instruction ID only relevant for "approval_response" type.
  string instruction_id = 5;

  // Optional approval response only relevant for "approval_response" type.
  string approval_response = 6;
}

// StreamOutput is the output message for the StreamFunction method.
// It contains the message counter, a flag indicating if this is the last message
message StreamOutput {
  // Counter for the message in the stream.
  int32 message_counter = 1;

  // Indicates if this is the last message in the stream.
  bool is_last = 2;

  // Value of the output.
  string value = 3;

  // Code validation of the output. Only relevant for code generation.
  string code_validation = 4;
}
