// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pkg/flowkitgrpc/flowkit.proto

package flowkitgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalFunctions_HealthCheck_FullMethodName    = "/flowkitgrpc.ExternalFunctions/HealthCheck"
	ExternalFunctions_GetVersion_FullMethodName     = "/flowkitgrpc.ExternalFunctions/GetVersion"
	ExternalFunctions_ListFunctions_FullMethodName  = "/flowkitgrpc.ExternalFunctions/ListFunctions"
	ExternalFunctions_RunFunction_FullMethodName    = "/flowkitgrpc.ExternalFunctions/RunFunction"
	ExternalFunctions_StreamFunction_FullMethodName = "/flowkitgrpc.ExternalFunctions/StreamFunction"
)

// ExternalFunctionsClient is the client API for ExternalFunctions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExternalFunctions is a gRPC service that allows for listing and running
// the function available in the externalfunctions package.
type ExternalFunctionsClient interface {
	// HealthCheck is a simple health check method that returns an empty response.
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetVersion returns the version of the service.
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Lists all available functions with description, inputs and outputs.
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error)
	// Runs a specified function with provided inputs and returns the function outputs.
	RunFunction(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FunctionInputs, FunctionOutputs], error)
	// Runs a specified function with provided inputs and returns the function output as a stream.
	// Accepts a stream of StreamInput messages to allow client-to-server interrupts.
	StreamFunction(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamInput, StreamOutput], error)
}

type externalFunctionsClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalFunctionsClient(cc grpc.ClientConnInterface) ExternalFunctionsClient {
	return &externalFunctionsClient{cc}
}

func (c *externalFunctionsClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ExternalFunctions_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalFunctionsClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, ExternalFunctions_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalFunctionsClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFunctionsResponse)
	err := c.cc.Invoke(ctx, ExternalFunctions_ListFunctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalFunctionsClient) RunFunction(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FunctionInputs, FunctionOutputs], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExternalFunctions_ServiceDesc.Streams[0], ExternalFunctions_RunFunction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FunctionInputs, FunctionOutputs]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalFunctions_RunFunctionClient = grpc.BidiStreamingClient[FunctionInputs, FunctionOutputs]

func (c *externalFunctionsClient) StreamFunction(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamInput, StreamOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExternalFunctions_ServiceDesc.Streams[1], ExternalFunctions_StreamFunction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamInput, StreamOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalFunctions_StreamFunctionClient = grpc.BidiStreamingClient[StreamInput, StreamOutput]

// ExternalFunctionsServer is the server API for ExternalFunctions service.
// All implementations must embed UnimplementedExternalFunctionsServer
// for forward compatibility.
//
// ExternalFunctions is a gRPC service that allows for listing and running
// the function available in the externalfunctions package.
type ExternalFunctionsServer interface {
	// HealthCheck is a simple health check method that returns an empty response.
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetVersion returns the version of the service.
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
	// Lists all available functions with description, inputs and outputs.
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error)
	// Runs a specified function with provided inputs and returns the function outputs.
	RunFunction(grpc.BidiStreamingServer[FunctionInputs, FunctionOutputs]) error
	// Runs a specified function with provided inputs and returns the function output as a stream.
	// Accepts a stream of StreamInput messages to allow client-to-server interrupts.
	StreamFunction(grpc.BidiStreamingServer[StreamInput, StreamOutput]) error
	mustEmbedUnimplementedExternalFunctionsServer()
}

// UnimplementedExternalFunctionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalFunctionsServer struct{}

func (UnimplementedExternalFunctionsServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedExternalFunctionsServer) GetVersion(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedExternalFunctionsServer) ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunctions not implemented")
}
func (UnimplementedExternalFunctionsServer) RunFunction(grpc.BidiStreamingServer[FunctionInputs, FunctionOutputs]) error {
	return status.Error(codes.Unimplemented, "method RunFunction not implemented")
}
func (UnimplementedExternalFunctionsServer) StreamFunction(grpc.BidiStreamingServer[StreamInput, StreamOutput]) error {
	return status.Error(codes.Unimplemented, "method StreamFunction not implemented")
}
func (UnimplementedExternalFunctionsServer) mustEmbedUnimplementedExternalFunctionsServer() {}
func (UnimplementedExternalFunctionsServer) testEmbeddedByValue()                           {}

// UnsafeExternalFunctionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalFunctionsServer will
// result in compilation errors.
type UnsafeExternalFunctionsServer interface {
	mustEmbedUnimplementedExternalFunctionsServer()
}

func RegisterExternalFunctionsServer(s grpc.ServiceRegistrar, srv ExternalFunctionsServer) {
	// If the following call panics, it indicates UnimplementedExternalFunctionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalFunctions_ServiceDesc, srv)
}

func _ExternalFunctions_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalFunctionsServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalFunctions_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalFunctionsServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalFunctions_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalFunctionsServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalFunctions_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalFunctionsServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalFunctions_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalFunctionsServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalFunctions_ListFunctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalFunctionsServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalFunctions_RunFunction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExternalFunctionsServer).RunFunction(&grpc.GenericServerStream[FunctionInputs, FunctionOutputs]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalFunctions_RunFunctionServer = grpc.BidiStreamingServer[FunctionInputs, FunctionOutputs]

func _ExternalFunctions_StreamFunction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExternalFunctionsServer).StreamFunction(&grpc.GenericServerStream[StreamInput, StreamOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalFunctions_StreamFunctionServer = grpc.BidiStreamingServer[StreamInput, StreamOutput]

// ExternalFunctions_ServiceDesc is the grpc.ServiceDesc for ExternalFunctions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalFunctions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowkitgrpc.ExternalFunctions",
	HandlerType: (*ExternalFunctionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ExternalFunctions_HealthCheck_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ExternalFunctions_GetVersion_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _ExternalFunctions_ListFunctions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunFunction",
			Handler:       _ExternalFunctions_RunFunction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamFunction",
			Handler:       _ExternalFunctions_StreamFunction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/flowkitgrpc/flowkit.proto",
}
