// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/agentgrpc/agent.proto

package agentgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage is the message sent by the client to the server.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ClientMessage_SessionContext
	//	*ClientMessage_ClientRequest
	MessageType   isClientMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMessageType() isClientMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ClientMessage) GetSessionContext() *SessionContext {
	if x != nil {
		if x, ok := x.MessageType.(*ClientMessage_SessionContext); ok {
			return x.SessionContext
		}
	}
	return nil
}

func (x *ClientMessage) GetClientRequest() *ClientRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ClientMessage_ClientRequest); ok {
			return x.ClientRequest
		}
	}
	return nil
}

type isClientMessage_MessageType interface {
	isClientMessage_MessageType()
}

type ClientMessage_SessionContext struct {
	// Session context message to initiate a session
	SessionContext *SessionContext `protobuf:"bytes,1,opt,name=session_context,json=sessionContext,proto3,oneof"`
}

type ClientMessage_ClientRequest struct {
	// Client request message to send a request to the server
	ClientRequest *ClientRequest `protobuf:"bytes,2,opt,name=client_request,json=clientRequest,proto3,oneof"`
}

func (*ClientMessage_SessionContext) isClientMessage_MessageType() {}

func (*ClientMessage_ClientRequest) isClientMessage_MessageType() {}

// ServerMessage is the message sent by the server to the client.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ServerMessage_ConnectionStatus
	//	*ServerMessage_AuthenticationStatus
	//	*ServerMessage_ClientResponse
	MessageType   isServerMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessageType() isServerMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ServerMessage) GetConnectionStatus() *ConnectionStatus {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_ConnectionStatus); ok {
			return x.ConnectionStatus
		}
	}
	return nil
}

func (x *ServerMessage) GetAuthenticationStatus() *AuthenticationStatus {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_AuthenticationStatus); ok {
			return x.AuthenticationStatus
		}
	}
	return nil
}

func (x *ServerMessage) GetClientResponse() *ClientResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServerMessage_ClientResponse); ok {
			return x.ClientResponse
		}
	}
	return nil
}

type isServerMessage_MessageType interface {
	isServerMessage_MessageType()
}

type ServerMessage_ConnectionStatus struct {
	// Connection status message to indicate the connection status after client sends a session context message
	ConnectionStatus *ConnectionStatus `protobuf:"bytes,1,opt,name=connection_status,json=connectionStatus,proto3,oneof"`
}

type ServerMessage_AuthenticationStatus struct {
	// Authentication status message to indicate failing authentication after client sends a session context message with authentication enabled
	AuthenticationStatus *AuthenticationStatus `protobuf:"bytes,2,opt,name=authentication_status,json=authenticationStatus,proto3,oneof"`
}

type ServerMessage_ClientResponse struct {
	// Client response message to send a response to the client
	ClientResponse *ClientResponse `protobuf:"bytes,3,opt,name=client_response,json=clientResponse,proto3,oneof"`
}

func (*ServerMessage_ConnectionStatus) isServerMessage_MessageType() {}

func (*ServerMessage_AuthenticationStatus) isServerMessage_MessageType() {}

func (*ServerMessage_ClientResponse) isServerMessage_MessageType() {}

// SessionContext is the message to initiate a session with the server.
type SessionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT token for authentication
	JwtToken string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	// Workflow ID for the workflow to be run
	WorkflowId string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Variables to be passed to the workflow
	Variables map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Snapshot ID; if defined, the given snapshot will retrived from the database
	SnapshotId string `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Workflow run ID; mandatory if "snapshot_id" is defined in order to retrieve the snapshot from the database
	WorkflowRunId string `protobuf:"bytes,5,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"`
	// User ID; mandatory if "snapshot_id" is defined in order to retrieve the snapshot from the database
	UserId string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Store snapshots; if true, all taken snapshots will be stored in the database
	StoreSnapshots bool `protobuf:"varint,7,opt,name=store_snapshots,json=storeSnapshots,proto3" json:"store_snapshots,omitempty"`
	// IP address of the client; required for some auth_types
	IpAddress string `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// API key for authentication
	ApiKey string `protobuf:"bytes,9,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Chat model ID; if defined, the given chat model will be used for the workflow run
	ChatModelId   string `protobuf:"bytes,10,opt,name=chat_model_id,json=chatModelId,proto3" json:"chat_model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SessionContext) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *SessionContext) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SessionContext) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SessionContext) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SessionContext) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *SessionContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionContext) GetStoreSnapshots() bool {
	if x != nil {
		return x.StoreSnapshots
	}
	return false
}

func (x *SessionContext) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SessionContext) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SessionContext) GetChatModelId() string {
	if x != nil {
		return x.ChatModelId
	}
	return ""
}

// ClientRequest is the message to send a request to the server.
type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instruction ID which has to be equal to the instruction ID of the client response for chat interface interaction
	InstructionId string `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Type of the request; can be "message", "get_variable_values", "set_variable_values", "keepalive", "take_snapshot", "load_snapshot", "get_slash_commands", "feedback", "get_conversation_title", "tool_validation", "code_execution", "parallel_code_execution", "edit_assitant_message", "set_chat_model", "approval_response"
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// String input for chat interface interaction
	Input string `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// Image input for chat interface interaction
	Images []string `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	// Variable values to be set for the workflow
	VariableValues map[string]string `protobuf:"bytes,5,rep,name=variable_values,json=variableValues,proto3" json:"variable_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ID of the snapshot to be loaded
	SnapshotId string `protobuf:"bytes,6,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Feedback for the workflow run
	Feedback *WorkflowFeedback `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"` // Feedback for the workflow run
	// Tool Call validation input
	AcceptToolCall bool `protobuf:"varint,8,opt,name=accept_tool_call,json=acceptToolCall,proto3" json:"accept_tool_call,omitempty"`
	// Updated LLM message after code changes for code execution
	UpdatedLlmMessage string `protobuf:"bytes,9,opt,name=updated_llm_message,json=updatedLlmMessage,proto3" json:"updated_llm_message,omitempty"`
	// Message ID of the conversation history message to be updated by edit_assistant_message request
	MessageId string `protobuf:"bytes,10,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Chat model ID to be set for the workflow run
	ChatModelId   string `protobuf:"bytes,11,opt,name=chat_model_id,json=chatModelId,proto3" json:"chat_model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ClientRequest) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *ClientRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ClientRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ClientRequest) GetVariableValues() map[string]string {
	if x != nil {
		return x.VariableValues
	}
	return nil
}

func (x *ClientRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ClientRequest) GetFeedback() *WorkflowFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ClientRequest) GetAcceptToolCall() bool {
	if x != nil {
		return x.AcceptToolCall
	}
	return false
}

func (x *ClientRequest) GetUpdatedLlmMessage() string {
	if x != nil {
		return x.UpdatedLlmMessage
	}
	return ""
}

func (x *ClientRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ClientRequest) GetChatModelId() string {
	if x != nil {
		return x.ChatModelId
	}
	return ""
}

// WorkflowFeedback is the message to send feedback to the server.
type WorkflowFeedback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID which has to be equal to the message ID in the conversation history for which the feedback is given
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Positive or negative feedback can either be added or removed to the message ID in the conversation history
	AddPositive    bool `protobuf:"varint,2,opt,name=add_positive,json=addPositive,proto3" json:"add_positive,omitempty"`
	AddNegative    bool `protobuf:"varint,3,opt,name=add_negative,json=addNegative,proto3" json:"add_negative,omitempty"`
	RemovePositive bool `protobuf:"varint,4,opt,name=remove_positive,json=removePositive,proto3" json:"remove_positive,omitempty"`
	RemoveNegative bool `protobuf:"varint,5,opt,name=remove_negative,json=removeNegative,proto3" json:"remove_negative,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkflowFeedback) Reset() {
	*x = WorkflowFeedback{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowFeedback) ProtoMessage() {}

func (x *WorkflowFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowFeedback.ProtoReflect.Descriptor instead.
func (*WorkflowFeedback) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowFeedback) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WorkflowFeedback) GetAddPositive() bool {
	if x != nil {
		return x.AddPositive
	}
	return false
}

func (x *WorkflowFeedback) GetAddNegative() bool {
	if x != nil {
		return x.AddNegative
	}
	return false
}

func (x *WorkflowFeedback) GetRemovePositive() bool {
	if x != nil {
		return x.RemovePositive
	}
	return false
}

func (x *WorkflowFeedback) GetRemoveNegative() bool {
	if x != nil {
		return x.RemoveNegative
	}
	return false
}

// ConnectionStatus is the message to indicate the connection status after client sends a session context message.
type ConnectionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection status; can be "success", "failed"
	ConnectionStatus string `protobuf:"bytes,1,opt,name=connectionStatus,proto3" json:"connectionStatus,omitempty"`
	// Workflow Run ID; if the connection status is "success", this will be the ID of the workflow run
	WorkflowRunId string `protobuf:"bytes,2,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"`
	// Maximum number of snapshots that can be stored in the database per workflow run
	MaxNumberOfSnapshots int32 `protobuf:"varint,3,opt,name=max_number_of_snapshots,json=maxNumberOfSnapshots,proto3" json:"max_number_of_snapshots,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectionStatus) GetConnectionStatus() string {
	if x != nil {
		return x.ConnectionStatus
	}
	return ""
}

func (x *ConnectionStatus) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *ConnectionStatus) GetMaxNumberOfSnapshots() int32 {
	if x != nil {
		return x.MaxNumberOfSnapshots
	}
	return 0
}

// AuthenticationStatus is the message to indicate failing authentication after client sends a session context message with authentication enabled.
type AuthenticationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication status; can only be "failed"
	AuthenticationStatus string `protobuf:"bytes,1,opt,name=authenticationStatus,proto3" json:"authenticationStatus,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthenticationStatus) Reset() {
	*x = AuthenticationStatus{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationStatus) ProtoMessage() {}

func (x *AuthenticationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationStatus.ProtoReflect.Descriptor instead.
func (*AuthenticationStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticationStatus) GetAuthenticationStatus() string {
	if x != nil {
		return x.AuthenticationStatus
	}
	return ""
}

// ClientResponse is the message to send a response to the client.
type ClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Randomly generated instruction ID to be used in the client request
	InstructionId string `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Type of the response; can be "message", "stream", "info_message", "info_stream", "error", "info", "varaible_values", "snapshot_taken", "snapshot_loaded", "slash_commands", "feedback_received", "conversation_title", "get_tool_validation", "code_execution_response", "assistant_message_edited", "status_message", "status_stream", "chat_model_set", "disable_interrupt", "enable_interrupt", "get_approval"
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Chat Interface properties
	IsLast           bool   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Position         uint32 `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	ChatData         string `protobuf:"bytes,5,opt,name=chat_data,json=chatData,proto3" json:"chat_data,omitempty"`
	CodeValidation   string `protobuf:"bytes,6,opt,name=code_validation,json=codeValidation,proto3" json:"code_validation,omitempty"` // "unvalidated", "valid", "warning", "invalid"
	InputTokenCount  int32  `protobuf:"varint,7,opt,name=input_token_count,json=inputTokenCount,proto3" json:"input_token_count,omitempty"`
	OutputTokenCount int32  `protobuf:"varint,8,opt,name=output_token_count,json=outputTokenCount,proto3" json:"output_token_count,omitempty"`
	Context          string `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	// Variable values properties
	VariableValues map[string]string `protobuf:"bytes,10,rep,name=variable_values,json=variableValues,proto3" json:"variable_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Snapshot properties; id of the snapshot taken or loaded
	SnapshotId string `protobuf:"bytes,11,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Slash command properties; List of @ commands containing their corresponding slash commands
	CommandsByCategory []*SlashCommandCategory `protobuf:"bytes,12,rep,name=commands_by_category,json=commandsByCategory,proto3" json:"commands_by_category,omitempty"`
	// Error properties
	Error *ErrorResponse `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	// Info properties
	InfoMessage *string `protobuf:"bytes,14,opt,name=info_message,json=infoMessage,proto3,oneof" json:"info_message,omitempty"`
	// Conversation Title
	ConversationTitle string `protobuf:"bytes,15,opt,name=conversation_title,json=conversationTitle,proto3" json:"conversation_title,omitempty"`
	// Tool Call properties
	ToolCall *ToolCall `protobuf:"bytes,16,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	// Code Execution properties
	CodeExecutionAllowed bool `protobuf:"varint,17,opt,name=code_execution_allowed,json=codeExecutionAllowed,proto3" json:"code_execution_allowed,omitempty"`
	// Images properties
	Images []string `protobuf:"bytes,18,rep,name=images,proto3" json:"images,omitempty"`
	// Stream interruption properties
	StreamInterruptionAllowed bool `protobuf:"varint,19,opt,name=stream_interruption_allowed,json=streamInterruptionAllowed,proto3" json:"stream_interruption_allowed,omitempty"`
	// Approval properties
	ApprovalText    string   `protobuf:"bytes,20,opt,name=approval_text,json=approvalText,proto3" json:"approval_text,omitempty"`
	ApprovalOptions []string `protobuf:"bytes,21,rep,name=approval_options,json=approvalOptions,proto3" json:"approval_options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ClientResponse) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *ClientResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *ClientResponse) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ClientResponse) GetChatData() string {
	if x != nil {
		return x.ChatData
	}
	return ""
}

func (x *ClientResponse) GetCodeValidation() string {
	if x != nil {
		return x.CodeValidation
	}
	return ""
}

func (x *ClientResponse) GetInputTokenCount() int32 {
	if x != nil {
		return x.InputTokenCount
	}
	return 0
}

func (x *ClientResponse) GetOutputTokenCount() int32 {
	if x != nil {
		return x.OutputTokenCount
	}
	return 0
}

func (x *ClientResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ClientResponse) GetVariableValues() map[string]string {
	if x != nil {
		return x.VariableValues
	}
	return nil
}

func (x *ClientResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ClientResponse) GetCommandsByCategory() []*SlashCommandCategory {
	if x != nil {
		return x.CommandsByCategory
	}
	return nil
}

func (x *ClientResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ClientResponse) GetInfoMessage() string {
	if x != nil && x.InfoMessage != nil {
		return *x.InfoMessage
	}
	return ""
}

func (x *ClientResponse) GetConversationTitle() string {
	if x != nil {
		return x.ConversationTitle
	}
	return ""
}

func (x *ClientResponse) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *ClientResponse) GetCodeExecutionAllowed() bool {
	if x != nil {
		return x.CodeExecutionAllowed
	}
	return false
}

func (x *ClientResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ClientResponse) GetStreamInterruptionAllowed() bool {
	if x != nil {
		return x.StreamInterruptionAllowed
	}
	return false
}

func (x *ClientResponse) GetApprovalText() string {
	if x != nil {
		return x.ApprovalText
	}
	return ""
}

func (x *ClientResponse) GetApprovalOptions() []string {
	if x != nil {
		return x.ApprovalOptions
	}
	return nil
}

// SlashCommandCategory is the message to send a list of slash commands categorized by their categories.
type SlashCommandCategory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the category
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// List of slash commands in this category
	Commands      []*SlashCommand `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlashCommandCategory) Reset() {
	*x = SlashCommandCategory{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashCommandCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashCommandCategory) ProtoMessage() {}

func (x *SlashCommandCategory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashCommandCategory.ProtoReflect.Descriptor instead.
func (*SlashCommandCategory) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SlashCommandCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SlashCommandCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SlashCommandCategory) GetCommands() []*SlashCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// SlashCommand is the message to send a slash command.
type SlashCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the slash command
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the slash command
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlashCommand) Reset() {
	*x = SlashCommand{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashCommand) ProtoMessage() {}

func (x *SlashCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashCommand.ProtoReflect.Descriptor instead.
func (*SlashCommand) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SlashCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SlashCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ToolCall is the message to send a tool call to the client.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the tool to be called
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of the tool
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Name of the tool
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Input parameters for the tool call
	Input         *structpb.Struct `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

// ErrorResponse is the message to send an error response to the client.
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agentgrpc_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agentgrpc_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_agentgrpc_agent_proto protoreflect.FileDescriptor

const file_pkg_agentgrpc_agent_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/agentgrpc/agent.proto\x12\tagentgrpc\x1a\x1cgoogle/protobuf/struct.proto\"\xa8\x01\n" +
	"\rClientMessage\x12D\n" +
	"\x0fsession_context\x18\x01 \x01(\v2\x19.agentgrpc.SessionContextH\x00R\x0esessionContext\x12A\n" +
	"\x0eclient_request\x18\x02 \x01(\v2\x18.agentgrpc.ClientRequestH\x00R\rclientRequestB\x0e\n" +
	"\fmessage_type\"\x89\x02\n" +
	"\rServerMessage\x12J\n" +
	"\x11connection_status\x18\x01 \x01(\v2\x1b.agentgrpc.ConnectionStatusH\x00R\x10connectionStatus\x12V\n" +
	"\x15authentication_status\x18\x02 \x01(\v2\x1f.agentgrpc.AuthenticationStatusH\x00R\x14authenticationStatus\x12D\n" +
	"\x0fclient_response\x18\x03 \x01(\v2\x19.agentgrpc.ClientResponseH\x00R\x0eclientResponseB\x0e\n" +
	"\fmessage_type\"\xbb\x03\n" +
	"\x0eSessionContext\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12F\n" +
	"\tvariables\x18\x03 \x03(\v2(.agentgrpc.SessionContext.VariablesEntryR\tvariables\x12\x1f\n" +
	"\vsnapshot_id\x18\x04 \x01(\tR\n" +
	"snapshotId\x12&\n" +
	"\x0fworkflow_run_id\x18\x05 \x01(\tR\rworkflowRunId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12'\n" +
	"\x0fstore_snapshots\x18\a \x01(\bR\x0estoreSnapshots\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x17\n" +
	"\aapi_key\x18\t \x01(\tR\x06apiKey\x12\"\n" +
	"\rchat_model_id\x18\n" +
	" \x01(\tR\vchatModelId\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x04\n" +
	"\rClientRequest\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x12U\n" +
	"\x0fvariable_values\x18\x05 \x03(\v2,.agentgrpc.ClientRequest.VariableValuesEntryR\x0evariableValues\x12\x1f\n" +
	"\vsnapshot_id\x18\x06 \x01(\tR\n" +
	"snapshotId\x127\n" +
	"\bfeedback\x18\a \x01(\v2\x1b.agentgrpc.WorkflowFeedbackR\bfeedback\x12(\n" +
	"\x10accept_tool_call\x18\b \x01(\bR\x0eacceptToolCall\x12.\n" +
	"\x13updated_llm_message\x18\t \x01(\tR\x11updatedLlmMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\n" +
	" \x01(\tR\tmessageId\x12\"\n" +
	"\rchat_model_id\x18\v \x01(\tR\vchatModelId\x1aA\n" +
	"\x13VariableValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x10WorkflowFeedback\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fadd_positive\x18\x02 \x01(\bR\vaddPositive\x12!\n" +
	"\fadd_negative\x18\x03 \x01(\bR\vaddNegative\x12'\n" +
	"\x0fremove_positive\x18\x04 \x01(\bR\x0eremovePositive\x12'\n" +
	"\x0fremove_negative\x18\x05 \x01(\bR\x0eremoveNegative\"\x9d\x01\n" +
	"\x10ConnectionStatus\x12*\n" +
	"\x10connectionStatus\x18\x01 \x01(\tR\x10connectionStatus\x12&\n" +
	"\x0fworkflow_run_id\x18\x02 \x01(\tR\rworkflowRunId\x125\n" +
	"\x17max_number_of_snapshots\x18\x03 \x01(\x05R\x14maxNumberOfSnapshots\"J\n" +
	"\x14AuthenticationStatus\x122\n" +
	"\x14authenticationStatus\x18\x01 \x01(\tR\x14authenticationStatus\"\xf1\a\n" +
	"\x0eClientResponse\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\rR\bposition\x12\x1b\n" +
	"\tchat_data\x18\x05 \x01(\tR\bchatData\x12'\n" +
	"\x0fcode_validation\x18\x06 \x01(\tR\x0ecodeValidation\x12*\n" +
	"\x11input_token_count\x18\a \x01(\x05R\x0finputTokenCount\x12,\n" +
	"\x12output_token_count\x18\b \x01(\x05R\x10outputTokenCount\x12\x18\n" +
	"\acontext\x18\t \x01(\tR\acontext\x12V\n" +
	"\x0fvariable_values\x18\n" +
	" \x03(\v2-.agentgrpc.ClientResponse.VariableValuesEntryR\x0evariableValues\x12\x1f\n" +
	"\vsnapshot_id\x18\v \x01(\tR\n" +
	"snapshotId\x12Q\n" +
	"\x14commands_by_category\x18\f \x03(\v2\x1f.agentgrpc.SlashCommandCategoryR\x12commandsByCategory\x12.\n" +
	"\x05error\x18\r \x01(\v2\x18.agentgrpc.ErrorResponseR\x05error\x12&\n" +
	"\finfo_message\x18\x0e \x01(\tH\x00R\vinfoMessage\x88\x01\x01\x12-\n" +
	"\x12conversation_title\x18\x0f \x01(\tR\x11conversationTitle\x120\n" +
	"\ttool_call\x18\x10 \x01(\v2\x13.agentgrpc.ToolCallR\btoolCall\x124\n" +
	"\x16code_execution_allowed\x18\x11 \x01(\bR\x14codeExecutionAllowed\x12\x16\n" +
	"\x06images\x18\x12 \x03(\tR\x06images\x12>\n" +
	"\x1bstream_interruption_allowed\x18\x13 \x01(\bR\x19streamInterruptionAllowed\x12#\n" +
	"\rapproval_text\x18\x14 \x01(\tR\fapprovalText\x12)\n" +
	"\x10approval_options\x18\x15 \x03(\tR\x0fapprovalOptions\x1aA\n" +
	"\x13VariableValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_info_message\"\x81\x01\n" +
	"\x14SlashCommandCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\bcommands\x18\x03 \x03(\v2\x17.agentgrpc.SlashCommandR\bcommands\"D\n" +
	"\fSlashCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"q\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12-\n" +
	"\x05input\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05input\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2V\n" +
	"\vWorkflowRun\x12G\n" +
	"\vRunWorkflow\x12\x18.agentgrpc.ClientMessage\x1a\x18.agentgrpc.ServerMessage\"\x00(\x010\x01B\rZ\v./agentgrpcb\x06proto3"

var (
	file_pkg_agentgrpc_agent_proto_rawDescOnce sync.Once
	file_pkg_agentgrpc_agent_proto_rawDescData []byte
)

func file_pkg_agentgrpc_agent_proto_rawDescGZIP() []byte {
	file_pkg_agentgrpc_agent_proto_rawDescOnce.Do(func() {
		file_pkg_agentgrpc_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agentgrpc_agent_proto_rawDesc), len(file_pkg_agentgrpc_agent_proto_rawDesc)))
	})
	return file_pkg_agentgrpc_agent_proto_rawDescData
}

var file_pkg_agentgrpc_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_agentgrpc_agent_proto_goTypes = []any{
	(*ClientMessage)(nil),        // 0: agentgrpc.ClientMessage
	(*ServerMessage)(nil),        // 1: agentgrpc.ServerMessage
	(*SessionContext)(nil),       // 2: agentgrpc.SessionContext
	(*ClientRequest)(nil),        // 3: agentgrpc.ClientRequest
	(*WorkflowFeedback)(nil),     // 4: agentgrpc.WorkflowFeedback
	(*ConnectionStatus)(nil),     // 5: agentgrpc.ConnectionStatus
	(*AuthenticationStatus)(nil), // 6: agentgrpc.AuthenticationStatus
	(*ClientResponse)(nil),       // 7: agentgrpc.ClientResponse
	(*SlashCommandCategory)(nil), // 8: agentgrpc.SlashCommandCategory
	(*SlashCommand)(nil),         // 9: agentgrpc.SlashCommand
	(*ToolCall)(nil),             // 10: agentgrpc.ToolCall
	(*ErrorResponse)(nil),        // 11: agentgrpc.ErrorResponse
	nil,                          // 12: agentgrpc.SessionContext.VariablesEntry
	nil,                          // 13: agentgrpc.ClientRequest.VariableValuesEntry
	nil,                          // 14: agentgrpc.ClientResponse.VariableValuesEntry
	(*structpb.Struct)(nil),      // 15: google.protobuf.Struct
}
var file_pkg_agentgrpc_agent_proto_depIdxs = []int32{
	2,  // 0: agentgrpc.ClientMessage.session_context:type_name -> agentgrpc.SessionContext
	3,  // 1: agentgrpc.ClientMessage.client_request:type_name -> agentgrpc.ClientRequest
	5,  // 2: agentgrpc.ServerMessage.connection_status:type_name -> agentgrpc.ConnectionStatus
	6,  // 3: agentgrpc.ServerMessage.authentication_status:type_name -> agentgrpc.AuthenticationStatus
	7,  // 4: agentgrpc.ServerMessage.client_response:type_name -> agentgrpc.ClientResponse
	12, // 5: agentgrpc.SessionContext.variables:type_name -> agentgrpc.SessionContext.VariablesEntry
	13, // 6: agentgrpc.ClientRequest.variable_values:type_name -> agentgrpc.ClientRequest.VariableValuesEntry
	4,  // 7: agentgrpc.ClientRequest.feedback:type_name -> agentgrpc.WorkflowFeedback
	14, // 8: agentgrpc.ClientResponse.variable_values:type_name -> agentgrpc.ClientResponse.VariableValuesEntry
	8,  // 9: agentgrpc.ClientResponse.commands_by_category:type_name -> agentgrpc.SlashCommandCategory
	11, // 10: agentgrpc.ClientResponse.error:type_name -> agentgrpc.ErrorResponse
	10, // 11: agentgrpc.ClientResponse.tool_call:type_name -> agentgrpc.ToolCall
	9,  // 12: agentgrpc.SlashCommandCategory.commands:type_name -> agentgrpc.SlashCommand
	15, // 13: agentgrpc.ToolCall.input:type_name -> google.protobuf.Struct
	0,  // 14: agentgrpc.WorkflowRun.RunWorkflow:input_type -> agentgrpc.ClientMessage
	1,  // 15: agentgrpc.WorkflowRun.RunWorkflow:output_type -> agentgrpc.ServerMessage
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_agentgrpc_agent_proto_init() }
func file_pkg_agentgrpc_agent_proto_init() {
	if File_pkg_agentgrpc_agent_proto != nil {
		return
	}
	file_pkg_agentgrpc_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_SessionContext)(nil),
		(*ClientMessage_ClientRequest)(nil),
	}
	file_pkg_agentgrpc_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_ConnectionStatus)(nil),
		(*ServerMessage_AuthenticationStatus)(nil),
		(*ServerMessage_ClientResponse)(nil),
	}
	file_pkg_agentgrpc_agent_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agentgrpc_agent_proto_rawDesc), len(file_pkg_agentgrpc_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agentgrpc_agent_proto_goTypes,
		DependencyIndexes: file_pkg_agentgrpc_agent_proto_depIdxs,
		MessageInfos:      file_pkg_agentgrpc_agent_proto_msgTypes,
	}.Build()
	File_pkg_agentgrpc_agent_proto = out.File
	file_pkg_agentgrpc_agent_proto_goTypes = nil
	file_pkg_agentgrpc_agent_proto_depIdxs = nil
}
